### ISSUE TITLE
please provide complete working code so that newbies would be able to grasp how to use

### ISSUE THREAD

**Issue by sanjayrautManish** [mr-easy/streaming_indicators#3]
please provide complete working code so that newbies would be able to grasp how to use

**Comment by sanjayrautManish** [comment]
you can point to indian stock market code that woud be more helpful
Thanks

**Comment by sanjayrautManish** [comment]
I tried to search working example code but not successful,phew

**Comment by mr-easy** [comment]
This project is in a very early stage, not much documentation has been created yet.
Readme is pretty much sufficient for getting started, just read it carefully. You need to load your data and give it to the indicator object. There is nothing required to be specific to Indian markets, this is general purpose, and can be used for candles from any market
This is an open-source project, and if you find problems in this you are free to contribute.
